# Generated by Django 4.2.18 on 2025-02-19 17:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("participant", "Participant"),
                            ("initiator", "Initiator"),
                            ("moderator", "Moderator"),
                        ],
                        default="participant",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningNuggetPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("learning_nugget", 10)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Title of the nugget", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Detailed description",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 130, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Please insert a short description of the video (character limit 500).",
                                    "max_length": 500,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV"
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("audio", "Audio file"),
                                        ("video", "Video file"),
                                    ]
                                },
                            ),
                            6: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ],
                                    "help_text": "You can add the video's transcript here (unlimited characters).",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 2),
                                        ("description", 3),
                                        ("media", 4),
                                        ("media_type", 5),
                                        ("transcript", 6),
                                    ]
                                ],
                                {
                                    "help_text": "Upload or select a video",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Upload related documents",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Thumbnail for the nugget",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("video", 7),
                                        ("document", 8),
                                        ("thumbnail", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nuggets",
                        to="learning_nuggets.learningcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
