# Generated by Django 4.2.18 on 2025-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_nuggets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
