# Generated by Django 4.2.18 on 2025-03-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_nuggets", "0002_learningcategory_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningnuggetpage",
            options={},
        ),
    ]
