# Generated by Django 4.2.18 on 2025-03-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_nuggets", "0003_alter_learningnuggetpage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningnuggetpage",
            options={"verbose_name": "Learning Nugget Page"},
        ),
    ]
