# Generated by Django 4.2.18 on 2025-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_settings", "0007_importantpages_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationsettings",
            name="platform_name",
            field=models.CharField(
                default="ROOTS Beteiligung",
                help_text="This name appears in the footer of all pages and e-mails as well as in the tab of the browser.",
                max_length=20,
                verbose_name="Platform name",
            ),
        ),
    ]
